/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.Component;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author shahad
 */
public class NewJFrame2 extends javax.swing.JFrame {
    NewJFrame jf = new NewJFrame();

    /**
     * Creates new form NewJFrame2
     */
    public NewJFrame2() {
        initComponents();

        ButtonGroup g=new ButtonGroup();
        g.add(login);
        g.add(register);
       
        panel(newuser,false);
    }

    
    public void panel(JPanel panel, boolean av){
      panel.setEnabled(av);
      
      Component[] c=panel.getComponents();
      
        for (int i = 0; i < c.length; i++) {
            if("javax.swing.JPanel".equals(c[i].getClass().getName())){
                panel((JPanel) c[i],av);
            }
            c[i].setEnabled(av);
        }
        
      //  setDefaultCloseOperation( EXIT_ON_CLOSE );
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        login = new javax.swing.JRadioButton();
        loginwin = new javax.swing.JPanel();
        username = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        register = new javax.swing.JRadioButton();
        newuser = new javax.swing.JPanel();
        fullname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        newpassword = new javax.swing.JPasswordField();
        newusername = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login.setSelected(true);
        login.setText("login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel1.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        loginwin.setBorder(javax.swing.BorderFactory.createTitledBorder("login"));
        loginwin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        loginwin.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 110, 30));

        jLabel3.setText("Password:");
        loginwin.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 30));

        jLabel4.setText("UserName:");
        loginwin.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));
        loginwin.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 110, 30));

        jButton1.setText("login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        loginwin.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        jPanel1.add(loginwin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 210, 230));

        register.setBackground(new java.awt.Color(255, 255, 255));
        register.setText("register");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        jPanel1.add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, -1, -1));

        newuser.setBorder(javax.swing.BorderFactory.createTitledBorder("new user"));
        newuser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fullname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullnameActionPerformed(evt);
            }
        });
        newuser.add(fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 110, 30));

        jLabel1.setText("Password:");
        newuser.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 30));

        jLabel2.setText("UserName:");
        newuser.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, 20));
        newuser.add(newpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 110, 30));

        newusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newusernameActionPerformed(evt);
            }
        });
        newuser.add(newusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 76, 110, 30));

        jLabel5.setText("Full Name");
        newuser.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 30));

        jButton2.setText("register");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        newuser.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jPanel1.add(newuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 210, 230));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 580, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fullnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullnameActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        panel(newuser,true);
        panel(loginwin,false);
    }//GEN-LAST:event_registerActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        panel(newuser,false);
        panel(loginwin,true);

        // TODO add your handling code here:
    }//GEN-LAST:event_loginActionPerformed

    private void newusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newusernameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            char[] pass = password.getPassword();
            String passString = new String(pass);
            
            if(jf.store.login(username.getText(),passString))    
            {
                Lastwin n = new Lastwin();
                n.setVisible(true);
                this.setVisible(false);
            } 
            else
                JOptionPane.showMessageDialog(rootPane, "user not found");
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NewJFrame2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            char[] pass = newpassword.getPassword();
            String passString = new String(pass);
            
            if(fullname.getText().equals("")){
                JOptionPane.showMessageDialog(rootPane, "FullName is Mandetory");
                return;
            }
            if(newusername.getText().equals("")){
                JOptionPane.showMessageDialog(rootPane,"UserName is Mandetory");
                 return;
            }
            if(passString.equals("")){
                JOptionPane.showMessageDialog(rootPane,"Password is Mandetory");
                 return;
            }
            
            
            if(jf.store.registerUser(fullname.getText(),newusername.getText(),passString))     //show this to shahad
            {
                Lastwin n = new Lastwin();
                n.setVisible(true);
                this.setVisible(false);
            }
            else
                JOptionPane.showMessageDialog(rootPane, "username exist, choose another useername");
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NewJFrame2.class.getName()).log(Level.SEVERE, null, ex);
        }
                
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("MAC OS X".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fullname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton login;
    private javax.swing.JPanel loginwin;
    private javax.swing.JPasswordField newpassword;
    private javax.swing.JPanel newuser;
    private javax.swing.JTextField newusername;
    private javax.swing.JPasswordField password;
    private javax.swing.JRadioButton register;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
